

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jamal
 */
public class Holiday1 extends javax.swing.JFrame {
LoginForm log = new LoginForm();
    /**
     * Creates new form Holiday1
     */
    public Holiday1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Meeting1 = new javax.swing.JButton();
        Tasks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RequestButton = new javax.swing.JButton();
        SearchText = new javax.swing.JTextField();
        SignOut = new javax.swing.JButton();
        Holiday = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        MOJY = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Meeting1.setBackground(new java.awt.Color(102, 102, 102));
        Meeting1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Meeting1.setText("Meeting");
        Meeting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meeting1ActionPerformed(evt);
            }
        });
        getContentPane().add(Meeting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 139, 57));

        Tasks.setBackground(new java.awt.Color(102, 102, 102));
        Tasks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tasks.setText("Tasks");
        Tasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TasksActionPerformed(evt);
            }
        });
        getContentPane().add(Tasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 139, 57));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("Type of Holiday :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("Start Date : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        RequestButton.setBackground(new java.awt.Color(204, 0, 0));
        RequestButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RequestButton.setText("Request");
        RequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 280, 57));

        SearchText.setBackground(new java.awt.Color(204, 204, 204));
        SearchText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextActionPerformed(evt);
            }
        });
        getContentPane().add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 25, 273, 48));

        SignOut.setBackground(new java.awt.Color(153, 0, 0));
        SignOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignOut.setText("Sign Out");
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });
        getContentPane().add(SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 25, 111, 48));

        Holiday.setBackground(new java.awt.Color(102, 102, 102));
        Holiday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Holiday.setText("Holiday");
        Holiday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HolidayActionPerformed(evt);
            }
        });
        getContentPane().add(Holiday, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 60));

        SearchButton.setBackground(new java.awt.Color(102, 102, 102));
        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchButton.setText("Search...");
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 25, 114, 48));

        MOJY.setFont(new java.awt.Font("Cooper Black", 1, 55)); // NOI18N
        MOJY.setText("MOJY");
        getContentPane().add(MOJY, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 60));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("End Date : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sick Holiday", "Yearly Holiday" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 130, 30));

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 130, 30));
        getContentPane().add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jamal\\Documents\\NetBeansProjects\\SoftProj\\images\\2222.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
        // TODO add your handling code here:
        log.Emp_ID = 0;
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_SignOutActionPerformed

    private void SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextActionPerformed

    private void RequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestButtonActionPerformed
        // TODO add your handling code here:
        if(jFormattedTextField1.getText().isEmpty() || jFormattedTextField2.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Insert your holiday Start and End Date");
            return;
        }
        try{      
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/swpro","root", "");
            Statement stmt = conn.createStatement();
            String sqlstr="INSERT INTO `vacation` (`ID`, `E_ID`, `VDate`, `endDate`, `holidayType`, `reply`) VALUES (NULL, '"+log.Emp_ID+"', '"+jFormattedTextField1.getText()+"', '"+jFormattedTextField2.getText()+"', '"+jComboBox1.getSelectedItem()+"', NULL)";
            stmt.executeUpdate(sqlstr);
            conn.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(Meeting1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RequestButtonActionPerformed

    private void TasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TasksActionPerformed
        // TODO add your handling code here:
        Tasks task = new Tasks();
        this.dispose();
        task.setVisible(true);
    }//GEN-LAST:event_TasksActionPerformed

    private void Meeting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meeting1ActionPerformed
        // TODO add your handling code here:
        Meeting meet = new Meeting();
        this.dispose();
        meet.setVisible(true);
    }//GEN-LAST:event_Meeting1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void HolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HolidayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HolidayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Holiday1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Holiday1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Holiday1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Holiday1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Holiday1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Holiday;
    private javax.swing.JLabel MOJY;
    private javax.swing.JButton Meeting1;
    private javax.swing.JButton RequestButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchText;
    private javax.swing.JButton SignOut;
    private javax.swing.JButton Tasks;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
