
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
class Vac{
    private String type;
    Date startDate,endDate;
    private int ID;
    
    public Vac(Date startDate, Date endDate, String type, int ID){
        this.type=type;
        this.startDate=startDate;
        this.endDate=endDate;
        this.ID=ID;
    }
   /* public int getid(){
        return ID;
}*/
       public String getType(){
        return type;
}
        public Date getStartDate(){
        return startDate;
}
         public Date getEndDate(){
        return endDate;
}
         public int getID(){
        return ID;
}
        
    
}
/**
 *
 * @author Msys
 */
public class vacations extends javax.swing.JFrame {
public static String Name;
public static int E_ID,noOfHolidays;

    /**
     * Creates new form Employees
     */
    public vacations() {
        initComponents();
        show_vacations();
    }
    public ArrayList<Vac> vacList(String sa){
    ArrayList<Vac> vacList =new ArrayList<>();
    
                  try{        
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/swpro","root", "");
        
            Statement stmt = conn.createStatement();
            String sqlstr="Select * FROM vacation where "+sa;
            ResultSet rs=stmt.executeQuery(sqlstr);
            //stmt.executeUpdate(sqlstr);
            
            
            Vac v;
            while(rs.next()){
                E_ID = rs.getInt("E_ID");
                Statement stmt1 = conn.createStatement();
                String sqlstr1="Select * FROM person where id = "+E_ID;
                
                ResultSet rs1=stmt1.executeQuery(sqlstr1);
                while(rs1.next()){
                    Name = rs1.getString("fName")+" "+rs1.getString("mName")+ " "+rs1.getString("lName");
                    noOfHolidays = rs1.getInt("no_Holidays");
                }
                
                v = new Vac(rs.getDate("VDate"),rs.getDate("endDate"),rs.getString("holidayType"),rs.getInt("ID"));
                vacList.add(v);
                
            }
            conn.close();
          /*  jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");*/
           //JOptionPane.showMessageDialog(this, "Successfully Added");
    }
        catch (SQLException ex) {
            Logger.getLogger(Meeting1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return vacList;          
    }
    public void show_vacations(){
        ArrayList<Vac> list=vacList("reply is NULL");
        DefaultTableModel model=(DefaultTableModel) vacations.getModel();
        Object []row =new Object[7];
        for(int i=0; i<list.size();i++){
            row[0]=Name;
            row[1]=E_ID;
            row[2]=list.get(i).getStartDate();
            row[3]=list.get(i).getEndDate();
            row[4]=noOfHolidays;
            row[5]=list.get(i).getType();
            row[6]=list.get(i).getID();
            model.addRow(row);
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vacations = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        search = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Holiday Manage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vacations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vacations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "E_ID", "Holiday date", "End Date", "no.Hol", "Type Of Holiday", "H_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vacations);
        if (vacations.getColumnModel().getColumnCount() > 0) {
            vacations.getColumnModel().getColumn(1).setMinWidth(50);
            vacations.getColumnModel().getColumn(1).setMaxWidth(10);
            vacations.getColumnModel().getColumn(4).setMinWidth(50);
            vacations.getColumnModel().getColumn(4).setMaxWidth(10);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 670, 200));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabel2.setText("search by:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 120, 30));

        jTextField5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(89, 146, 204));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 130, 25));

        jButton1.setBackground(new java.awt.Color(89, 146, 204));
        jButton1.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 330, 30));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 80, -1));

        search.setBackground(new java.awt.Color(89, 146, 204));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", " " }));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 70, 25));

        jButton3.setBackground(new java.awt.Color(89, 146, 204));
        jButton3.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Refusal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 140, -1));

        jButton4.setBackground(new java.awt.Color(89, 146, 204));
        jButton4.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Acceptance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jamal\\Documents\\NetBeansProjects\\SoftProj\\images\\holiday.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -10, 1010, 380));

        setSize(new java.awt.Dimension(719, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField5.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Vacation ID");
            return;
        }
        try{
            int v_id = Integer.parseInt(jTextField5.getText());
            ArrayList<Vac> list=vacList("ID = "+v_id);
            DefaultTableModel model=(DefaultTableModel) vacations.getModel();
            model.setRowCount(0);
            Object []row =new Object[7];
            for(int i=0; i<list.size();i++){
                row[0]=Name;
                row[1]=E_ID;
                row[2]=list.get(i).getStartDate();
                row[3]=list.get(i).getEndDate();
                row[4]=noOfHolidays;
                row[5]=list.get(i).getType();
                row[6]=list.get(i).getID();
                model.addRow(row);
        }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Vacation ID must be Number only");
            jTextField5.setText("");
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Main frame = new Main();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(vacations.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Please select Vacation from the table");
            return;
        }
        int column = 6;
        int row = vacations.getSelectedRow();
        String value = vacations.getModel().getValueAt(row, column).toString();
        int v_id = Integer.parseInt(value);
        try{        
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/swpro","root", "");
            Statement stmt = conn.createStatement();
            String sqlstr="UPDATE `vacation` SET `reply` = 'Rejected' WHERE `vacation`.`ID` = "+v_id;
            stmt.executeUpdate(sqlstr);
            conn.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(Meeting1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(vacations.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Please select Vacation from the table");
            return;
        }
        int column = 6;
        int row = vacations.getSelectedRow();
        String value = vacations.getModel().getValueAt(row, column).toString();
        int v_id = Integer.parseInt(value);
        try{        
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/swpro","root", "");
            Statement stmt = conn.createStatement();
            String sqlstr="UPDATE `vacation` SET `reply` = 'Accepted' WHERE `vacation`.`ID` = "+v_id;
            stmt.executeUpdate(sqlstr);
            conn.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(Meeting1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vacations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox<String> search;
    private javax.swing.JTable vacations;
    // End of variables declaration//GEN-END:variables
}
